-- データベース dokoTsubu
-- ユーザー名 sa
-- パスワード (no)

CREATE TABLE MUTTERS (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR (100) NOT NULL,
 TEXT VARCHAR (255) NOT NULL
);
INSERT INTO MUTTERS (NAME, TEXT) VALUES ('湊', '今日は休みだ');
INSERT INTO MUTTERS (NAME, TEXT) VALUES ('綾部', 'いいな〜');